# project_config.yaml

# 1. Hardware / Global Settings
resources:
  host: "rigi"
  username: "lege"
  n_cores: 1
  mem_per_core: 2000 # MB
  max_concurrent_jobs: 100
  
# 2. Chemistry Defaults
chemistry:
  charge: 0
  multiplicity: 1 # Default, can be overridden by job_data
  functional: ["BP86", "B3LYP"]
  basis_set: "sv"
  dispersion: "D4"
  aux_basis: "def2/J"
    #  solvation: "CPCM(ACETONE)"

# 3. The Pipelines (The "different treatments")
pipelines:
  
  # --- Profile A: The "Full Monty" (Reactants) ---
  # Computes everything: UV/Vis, Raman, Moessbauer
  reactant_full_spec:
    optimization:
      next_steps:
        - stage: frequency
          folder: "02_Freq"
          validation_mode: "minimum" # Special validation logic
    
    frequency:
      next_steps: [] # Leaf node
      functional: "PBE"

  # --- Profile B: The "Exotic Intermediate" ---
  # Skips UV/Vis, adds EPR and XAS
  intermediate_epr_xas:
    optimization:
      next_steps:
          
    optimization: 
      next_steps: []
    # ... etc ...
